### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by sadrasabouri** [sepandhaghighi/samila#1]
## Tasks
- [x] Functions docstring 
- [x] A Proper README.md file should be provided. (Also we can use later repository README.md file as a template)
- [x] Complete `MINIMAL_DESCRIPTION` from [here](https://github.com/sepandhaghighi/samila/blob/dev/setup.py#L9).
- [x] Complete `long_description` from [here](https://github.com/sepandhaghighi/samila/blob/dev/setup.py#L37).
- [x] Add proper `About` section for Github repository.
- [x] Add some examples
- [x] `CONTRIBUTING.md`
- [x] `CODE_OF_CONDUCT.md`
- [x] `INSTALL.md`

**Comment by sadrasabouri** [comment]
@sepandhaghighi 
Can you fill `About` section and add some tags?
I don't have that access.

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi Can you fill `About` section and add some tags? I don't have that access.

Consider it done
